[sssd]
config_file_version = 2
services = nss, pam, ssh
domains = nasa.csie.ntu

[nss]
filter_users = root
filter_groups = root

[pam]
offline_credentials_expiration = 60

[domain/nasa.csie.ntu]
id_provider = ldap
auth_provider = ldap
chpass_provider = ldap
access_provider = ldap

ldap_uri = ldaps://192.168.8.1
ldap_search_base = dc=nasa,dc=csie,dc=ntu

ldap_tls_reqcert = allow
ldap_tls_cacert = /etc/openldap/certs/ca-cert.pem

ldap_user_search_base = ou=people,dc=nasa,dc=csie,dc=ntu
ldap_group_search_base = ou=group,dc=nasa,dc=csie,dc=ntu

ldap_schema = rfc2307bis
ldap_user_object_class = inetOrgPerson
ldap_group_object_class = posixGroup

ldap_user_name = uid
ldap_user_uid_number = uidNumber
ldap_user_gid_number = gidNumber
ldap_user_home_directory = homeDirectory
ldap_user_shell = loginShell
ldap_group_name = cn
ldap_group_gid_number = gidNumber
ldap_group_member = memberUid

ldap_access_order = filter
ldap_access_filter = (objectClass=posixAccount)

cache_credentials = true
enumerate = false

override_homedir = /home/%u
fallback_homedir = /home/%u

